const router = require('express').Router();
const { body } = require('express-validator');
const asyncHandler = require('../utils/asyncHandler');
const auth = require('../controllers/authController');
const { authLimiter, otpLimiter } = require('../middlewares/rateLimits');
const passwordRule = body('password').matches(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$/).withMessage('Password minimal 8 karakter dan harus memiliki huruf besar, kecil, dan angka.');
router.get('/captcha.svg', asyncHandler(auth.captchaImage));
router.get('/register', auth.renderRegister);
router.post('/register', authLimiter, body('name').trim().isLength({ min: 2, max: 80 }).withMessage('Nama harus 2-80 karakter.'), body('email').isEmail().normalizeEmail().withMessage('Email tidak valid.'), passwordRule, body('confirmPassword').custom((value, { req }) => value === req.body.password).withMessage('Konfirmasi password tidak cocok.'), asyncHandler(auth.register));
router.get('/login', auth.renderLogin);
router.post('/login', authLimiter, body('email').isEmail().normalizeEmail().withMessage('Email tidak valid.'), body('password').notEmpty().withMessage('Password wajib diisi.'), asyncHandler(auth.login));
router.get('/otp/:flow', auth.renderOtp);
router.post('/otp/:flow', otpLimiter, body('code').matches(/^\d{6}$/).withMessage('OTP harus enam digit.'), asyncHandler(auth.verifyOtpFlow));
router.post('/otp/:flow/resend', otpLimiter, asyncHandler(auth.resendOtp));
router.get('/forgot-password', auth.renderForgot);
router.post('/forgot-password', authLimiter, body('email').isEmail().normalizeEmail().withMessage('Email tidak valid.'), asyncHandler(auth.forgot));
router.get('/reset-password', auth.renderReset);
router.post('/reset-password', passwordRule, body('confirmPassword').custom((value, { req }) => value === req.body.password).withMessage('Konfirmasi password tidak cocok.'), asyncHandler(auth.resetPassword));
router.post('/logout', auth.logout);
module.exports = router;
