const mongoose = require('mongoose');
const itemSchema = new mongoose.Schema({
  product: { type: mongoose.Schema.Types.ObjectId, ref: 'Product', required: true },
  name: { type: String, required: true },
  slug: { type: String, required: true },
  thumbnail: String,
  unitPrice: { type: Number, required: true },
  quantity: { type: Number, required: true, min: 1 },
  stockReservationQuantity: { type: Number, min: 0, default: 0 },
  lineTotal: { type: Number, required: true },
  version: String,
  downloadLimit: { type: Number, default: 5 },
  downloadsUsed: { type: Number, default: 0 }
}, { _id: false });
const schema = new mongoose.Schema({
  orderNumber: { type: String, required: true, unique: true, index: true },
  invoiceNumber: { type: String, required: true, unique: true, index: true },
  idempotencyKey: { type: String, required: true, unique: true, index: true },
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
  buyerSnapshot: { name: String, email: String },
  items: [itemSchema],
  itemsSubtotal: { type: Number, min: 0, default: 0 },
  discountCode: { type: mongoose.Schema.Types.ObjectId, ref: 'DiscountCode', default: null, index: true },
  discountCodeText: { type: String, default: '' },
  discountName: { type: String, default: '' },
  discountKind: { type: String, enum: ['voucher', 'promo', ''], default: '' },
  discountType: { type: String, enum: ['percentage', 'fixed', ''], default: '' },
  discountValue: { type: Number, min: 0, default: 0 },
  discountScope: { type: String, enum: ['all', 'products', ''], default: '' },
  discountAmount: { type: Number, min: 0, default: 0 },
  discountReserved: { type: Boolean, default: false },
  discountCommitted: { type: Boolean, default: false },
  discountReleased: { type: Boolean, default: false },
  subtotal: { type: Number, required: true, min: 0 },
  walletAmount: { type: Number, required: true, min: 0, default: 0 },
  externalSubtotal: { type: Number, required: true, min: 0, default: 0 },
  walletCommitted: { type: Boolean, default: false },
  walletReleased: { type: Boolean, default: false },
  gatewayFee: { type: Number, required: true, min: 0 },
  userFee: { type: Number, required: true, min: 0 },
  merchantFee: { type: Number, required: true, min: 0 },
  merchantNet: { type: Number, required: true },
  total: { type: Number, required: true, min: 0 },
  pakasirAmount: { type: Number, required: true, min: 0 },
  paymentMethod: { type: String, required: true },
  paymentChannel: { type: String, enum: ['free', 'wallet', 'gateway', 'hybrid'], default: 'gateway', index: true },
  pakasirTransactionId: { type: String, unique: true, index: true, sparse: true },
  paymentNumber: String,
  paymentQrDataUrl: { type: String, select: false },
  paymentStatus: { type: String, enum: ['initializing', 'pending', 'paid', 'failed', 'expired', 'cancelled', 'refunded', 'compensation_required'], default: 'initializing', index: true },
  orderStatus: { type: String, enum: ['awaiting_payment', 'processing', 'fulfilled', 'cancelled', 'refund'], default: 'awaiting_payment', index: true },
  expiresAt: Date,
  paidAt: Date,
  lastWebhookData: mongoose.Schema.Types.Mixed,
  stockReserved: { type: Boolean, default: false },
  stockCommitted: { type: Boolean, default: false },
  stockReleased: { type: Boolean, default: false },
  accessGranted: { type: Boolean, default: false },
  cancellationInProgress: { type: Boolean, default: false, select: false },
  maintenanceLockedAt: { type: Date, default: null, select: false },
  maintenanceLockId: { type: String, default: '', select: false },
  cancelledAt: Date,
  cancellationReason: { type: String, maxlength: 300, default: '' },
  cancelledBy: { type: String, enum: ['user', 'admin', 'system'], default: undefined },
  cancellationResponse: mongoose.Schema.Types.Mixed,
  compensation: {
    required: { type: Boolean, default: false, index: true },
    attempts: { type: Number, default: 0 },
    lastError: String,
    lastAttemptAt: Date
  },
  notifications: {
    paidSent: { type: Boolean, default: false },
    expiredSent: { type: Boolean, default: false },
    invoiceSent: { type: Boolean, default: false }
  }
}, { timestamps: true });
module.exports = mongoose.model('Order', schema);
